```{r child=ifelse("ICESat2VegR" %in% names(sessionInfo()$otherPkgs), "", "../basic/01load.Rmd")}
```

```{r child=ifelse(exists("atl03_h5"), "", "../basic/02openFiles.Rmd")}
```

## Extract attributes

```{r, results = 'hide'}
# ATL03 seg attributes
atl03_seg_dt <- ATL03_seg_attributes_dt(atl03_h5, attributes = c("delta_time", "solar_elevation", "pitch", "h_ph", "ref_elev"))

head(atl03_seg_dt)
```


```{r, echo = FALSE}
print(head(atl03_seg_dt))
```


```{r, results = 'hide'}
# ATL08 seg attributes
atl08_seg_dt <- ATL08_seg_attributes_dt(atl08_h5, attributes = c("h_canopy", "h_te_mean", "terrain_slope", "canopy_openness"))

head(atl08_seg_dt)
```

```{r, echo = FALSE}
head(atl08_seg_dt)
```

```{r, echo = FALSE, results = 'hide'}
# ATL08 seg attributes
atl08_seg_dt <- ATL08_seg_attributes_dt(atl08_h5, attributes = c("h_canopy", "h_te_mean", "terrain_slope", "canopy_openness"))

head(atl08_seg_dt)
```

Plot histograms:

```{r, eval = FALSE}
layout(t(1:2))

# ATL03 height histogram
hist(atl03_seg_dt$ref_elev, col = "#bd8421", xlab = "Elevation (m)", main = "h_te_mean")
hist(atl08_seg_dt$h_canopy, col = "green", xlab = "height (m)", main = "h_canopy")
```

<div align="center">

```{r echo = FALSE, fig.cap = 'Histograms for ATL03 elevation and ATL08 h_canopy', fig.align="center"}
layout(t(1:2))

# ATL03 height histogram
hist(atl03_seg_dt$ref_elev, col = "#bd8421", xlab = "Elevation (m)", main = "h_te_mean")
hist(atl08_seg_dt$h_canopy, col = "green", xlab = "height (m)", main = "h_canopy")
```

</div>

## Export to vector
The function `to_vect()` will return a `terra::vect` object.


```{r export_vector03, message = FALSE, out.width='50%', fig.cap="ATL03 segments elevation preview on leaflet map."}
library(terra)

atl03_seg_vect <- to_vect(atl03_seg_dt)

# Plot with terra::plet
terra::plet(
  atl03_seg_vect,
  "ref_elev",
  label = TRUE,
  breaks = 3,
  tiles = c("Esri.WorldImagery")
) |> leaflet::setView(zoom = 16, lat = 41.53545, lng = -106.5703)
```

```{r export_vector08, out.width='50%', fig.cap='ATL08 segments preview on leaflet map.'}
atl08_seg_vect <- to_vect(atl08_seg_dt)

# Plot with terra::plet
map_vect <- terra::plet(
  atl08_seg_vect,
  "h_canopy",
  col = grDevices::hcl.colors(100, "RdYlGn", rev = TRUE),
  type = "interval",
  breaks = 3,
  tiles = c("Esri.WorldImagery"),
  label = TRUE,
  decreasing = TRUE
) |> leaflet::setView(zoom = 15, lat = 41.53545, lng = -106.5703)

map_vect
```

Save vector as geopackage file. The formats supported are as from GDAL terra package.

```{r write_vector, eval = FALSE}
terra::writeVector(atl03_seg_vect, "atl03_seg.gpkg")
terra::writeVector(atl08_seg_vect, "atl08_seg.gpkg")
```

## View ATL08 segments as raster

Single max_h_canopy:

```{r, out.width='50%', fig.cap='ATL08 rasterized segments preview on leaflet map.'}
max_h_canopy <- ATL08_seg_attributes_dt_gridStat(atl08_seg_dt, func = max(h_canopy), res = 0.001)
red_yellow_green_palette <- grDevices::hcl.colors(100, "RdYlGn")

terra::plet(max_h_canopy,
  legend = "bottomleft",
  main = "Max 'h_canopy'",
  map = map_vect,
  col = red_yellow_green_palette
)
```

Multiple data:

```{r out.width='50%'}
multiple_data <- ATL08_seg_attributes_dt_gridStat(atl08_seg_dt, func = list(
  max_h_canopy = max(h_canopy),
  min_h_canopy = min(h_canopy),
  mean_canopy_openness = mean(canopy_openness),
  mean_h_te_mean = mean(h_te_mean)
), res = 0.002)

map_vect_openness <- terra::plet(
  atl08_seg_vect,
  "canopy_openness",
  col = red_yellow_green_palette,
  type = "interval",
  breaks = 3,
  tiles = c("Esri.WorldImagery"),
  label = TRUE
) |> leaflet::setView(zoom = 15, lat = 41.53545, lng = -106.5703)

map_vect_terrain <- terra::plet(
  atl08_seg_vect,
  "h_te_mean",
  col = grDevices::hcl.colors(100, "RdYlBu", rev = TRUE),
  type = "interval",
  breaks = 3,
  tiles = c("Esri.WorldImagery"),
  label = TRUE
) |> leaflet::setView(zoom = 15, lat = 41.53545, lng = -106.5703)


map1 <- terra::plet(multiple_data[[1]], legend = "bottomleft", map = map_vect, col = red_yellow_green_palette)
map2 <- terra::plet(multiple_data[[2]], legend = "bottomleft", map = map_vect, col = red_yellow_green_palette)
map3 <- terra::plet(multiple_data[[3]], legend = "bottomleft", map = map_vect_openness, col = red_yellow_green_palette)
map4 <- terra::plet(multiple_data[[4]], col = grDevices::hcl.colors(100, "RdYlBu", rev = TRUE), legend = "bottomleft", map = map_vect_terrain)
```


```{r, fig.cap = 'Rasterized maximum h_canopy', out.width = '50%'}
map1
```

```{r, fig.cap = 'Rasterized minimum h_canopy', out.width = '50%'}
map2
```

```{r, fig.cap = 'Rasterized mean canopy openness', out.width = '50%'}
map3
```

```{r, fig.cap = 'Rasterized mean terrain height', out.width = '50%'}
map4
```