```{r include = FALSE}
if (!exists("basic_path")) {
  basic_path <- "../basic"
}
```

```{r child=file.path(basic_path, "01load.Rmd")}
```

```{r child=file.path(basic_path, "02openFiles.Rmd")}
```

```{r, include = FALSE}
if (!exists("atl03_atl08_dt")) {
  atl03_atl08_dt <- ATL03_ATL08_photons_attributes_dt_join(atl03_h5, atl08_h5, beam = "gt1r")
}
```

```{r, echo = FALSE, results = 'hide'}
atl03_atl08_dt <- ATL03_ATL08_photons_attributes_dt_join(atl03_h5, atl08_h5, beam = "gt1r")
```

<div align="center" style="overflow-x: scroll;">

```{r echo = FALSE, results = 'asis'}
head(atl03_atl08_dt)
```

</div>

## Plotting the result:
```{r, eval = FALSE}
oldpar <- par(no.readonly = TRUE)
par(oma = c(0, 0, 0, 0))
par(mar = c(2, 3, 1, 1))
layout(matrix(c(1, 2), ncol = 1))
plot(
  atl03_atl08_dt,
  y = "h_ph",
  colors = c("gray", "#bd8421", "forestgreen", "green"),
  xlim = range(atl03_atl08_dt$dist_ph_along),
  ylim = range(atl03_atl08_dt$h_ph),
  beam = "gt1r",
  cex = 0.5,
  pch = 16
)

par(mar = c(3, 3, 1, 1))

plot(
  atl03_atl08_dt,
  y = "ph_h",
  colors = c("gray", "#bd8421", "forestgreen", "green"),
  xlim = range(atl03_atl08_dt$dist_ph_along),
  ylim = range(atl03_atl08_dt$ph_h),
  beam = "gt1r",
  cex = 0.5,
  pch = 16
)

par(
  oldpar
)
```

<div align="center">

```{r, echo = FALSE, fig.align = 'center', fig.cap = 'Classified ATL03 photons using ATL08 labels', fig.width=5, fig.height=5}
oldpar <- par(no.readonly = TRUE)
par(oma = c(0, 0, 0, 0))
par(mar = c(2, 3, 1, 1))
layout(matrix(c(1, 2), ncol = 1))
plot(
  atl03_atl08_dt,
  y = "h_ph",
  colors = c("gray", "#bd8421", "forestgreen", "green"),
  xlim = range(atl03_atl08_dt$dist_ph_along),
  ylim = range(atl03_atl08_dt$h_ph),
  beam = "gt1r",
  cex = 0.5,
  pch = 16
)

par(mar = c(3, 3, 1, 1))

plot(
  atl03_atl08_dt,
  y = "ph_h",
  colors = c("gray", "#bd8421", "forestgreen", "green"),
  xlim = range(atl03_atl08_dt$dist_ph_along),
  ylim = range(atl03_atl08_dt$ph_h),
  beam = "gt1r",
  cex = 0.5,
  pch = 16
)

par(
  oldpar
)
```

</div>

## Calculating raster statistics

```{r, eval = FALSE}
h_canopy <- ATL03_ATL08_photons_attributes_dt_gridStat(
  atl03_atl08_dt,
  func = list(h_canopy = quantile(ph_h, 0.98), count = .N),
  res = 0.0001
)

plot(h_canopy,
  col = viridis::inferno(100),
  xlab = "Langitude (degree)",
  ylab = "Latitude (degree)"
)
```

<div align="center">

```{r, echo = FALSE, fig.align = 'center', fig.cap = 'Rasterized ATL03_ATL08 data for canopy height (h_canopy) and number of photons (n)', echo = FALSE, fig.width=5, fig.height=4}
h_canopy <- ATL03_ATL08_photons_attributes_dt_gridStat(
  atl03_atl08_dt,
  func = list(h_canopy = quantile(ph_h, 0.98), count = .N),
  res = 0.0001
)

plot(h_canopy,
  col = viridis::inferno(100),
  xlab = "Langitude (degree)",
  ylab = "Latitude (degree)"
)
```

</div>
