#' Export Merged ICESat-2 ATL03/ATL08 Photon Data to LAS Files
#'
#' @description
#' Converts the merged ATL03/ATL08 photon dataset generated by
#' \code{ATL03_ATL08_photons_attributes_dt_join()} into one or more LAS files.
#' The output preserves ATL03 photon geolocation and elevation information
#' together with ATL08 photon classifications and normalized heights, enabling
#' the resulting point cloud to be visualized and analyzed in standard LiDAR
#' software.
#'
#' @param atl03_atl08_dt An S4 object of class
#' \code{ICESat2VegR::icesat2.atl08_dt-class} or a \code{data.table}
#' containing ATL03 and ATL08 photon data, usually the output of
#' \code{ATL03_ATL08_photons_attributes_dt_join()}.
#' @param output Character. Output LAS file path. The function creates one LAS
#' file per UTM zone in the WGS84 datum.
#' @param normalized Logical. If \code{TRUE}, writes normalized ATL08 photon
#' height \code{ph_h}; if \code{FALSE}, writes raw ATL03 photon height
#' \code{h_ph}. Default is \code{TRUE}.
#'
#' @return Invisibly returns a character vector with the written LAS file paths.
#'
#' @details
#' This function converts the output of
#' \code{ATL03_ATL08_photons_attributes_dt_join()} to LAS format using the
#' package internal \code{dt_to_las()} and \code{writeLAS()} functions.
#'
#' The input table must contain photon longitude, photon latitude, ATL03 photon
#' height, ATL08 normalized photon height, and ATL08 photon classification.
#'
#' If \code{normalized = TRUE}, the \code{ph_h} column is used as the LAS Z
#' coordinate. If \code{normalized = FALSE}, the raw ATL03 \code{h_ph} column is
#' used as the LAS Z coordinate.
#'
#' Photon classes are written to the LAS \code{Classification} field using
#' \code{classed_pc_flag + 1}.
#'
#' Because LAS files require projected coordinates, the longitude and latitude
#' values are split by UTM zone and projected to the corresponding UTM CRS before
#' writing. One LAS file is created per UTM zone. The internal UTM-zone assignment
#' follows helper routines based on the latitude/longitude to UTM conversion
#' algorithms developed by Chuck Gantz.
#'
#' @references
#' Gantz, C. Latitude/Longitude to UTM Conversion Algorithms.
#' \url{https://oceancolor.gsfc.nasa.gov/docs/ocssw/LatLong-UTMconversion_8cpp_source.html}
#'
#' @examples
#' \dontrun{
#' outdir <- tempdir()
#'
#' atl03_path <- system.file("extdata", "atl03_clip.h5", package = "ICESat2VegR")
#' atl08_path <- system.file("extdata", "atl08_clip.h5", package = "ICESat2VegR")
#'
#' atl03_h5 <- ATL03_read(atl03_path = atl03_path)
#' atl08_h5 <- ATL08_read(atl08_path = atl08_path)
#'
#' atl03_atl08_dt <- ATL03_ATL08_photons_attributes_dt_join(
#'   atl03_h5,
#'   atl08_h5
#' )
#'
#' ATL03_ATL08_photons_attributes_dt_LAS(
#'   atl03_atl08_dt,
#'   output = file.path(outdir, "output.las"),
#'   normalized = TRUE
#' )
#'
#' close(atl03_h5)
#' close(atl08_h5)
#' }
#'
#' @include lasTools.R
#' @importFrom data.table as.data.table
#'
#' @export
ATL03_ATL08_photons_attributes_dt_LAS <- function(
    atl03_atl08_dt,
    output,
    normalized = TRUE
) {

  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.")
  }

  if (!is.logical(normalized) || length(normalized) != 1) {
    stop("normalized must be TRUE or FALSE.")
  }

  atl03_atl08_dt <- data.table::as.data.table(atl03_atl08_dt)
  atl03_atl08_dt <- stats::na.omit(atl03_atl08_dt)

  z_col <- if (normalized) "ph_h" else "h_ph"

  required_cols <- c("lon_ph", "lat_ph", z_col, "classed_pc_flag")

  if (!all(required_cols %in% names(atl03_atl08_dt))) {
    stop(
      "atl03_atl08_dt must contain the columns: ",
      paste(required_cols, collapse = ", "),
      "."
    )
  }

  lon_ph <- lat_ph <- classed_pc_flag <- NULL

  dt <- data.table::as.data.table(atl03_atl08_dt[, list(
    X = lon_ph,
    Y = lat_ph,
    Z = get(z_col),
    Classification = as.integer(classed_pc_flag + 1)
  )])

  dt_to_las(dt, output)
}
