# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findRadius <- function(x, y, radius, sampleSize) {
    .Call('_ICESat2VegR_findRadius', PACKAGE = 'ICESat2VegR', x, y, radius, sampleSize)
}

