name: R-universe build test

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: R-universe build test
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
